services:
    acme_user.registration.form.type:
        class: Acme\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: acme_user_registration }
    acme_user.registration_success:
        class: Acme\UserBundle\EventListener\RegistrationSuccessListener
        arguments: 
        tags:
            - { name: kernel.event_subscriber }
            